apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 2401082-videosummdocker-ingress
  namespace: 2401082-videosummdocker
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
    # Add other annotations if using specific Ingress Controller features
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-2401082-videosummdocker
            port:
              number: 80
